[service]
# Port on which the service will run
port = 30445

[service.signer]
# secpr256k1 32-byte hex-encoded private key, used for signing,
# this is a example key, do not use it anywhere else
private_key = "804622cda0d8e634317a12651d91751ceff5c081f2b5f63ef7912725c7275e5d"

[service.db] # Postgres database configuration
url = "localhost:5432"
username = "oracle"
password = "oracle"
database = "price_oracle"

[service.feed_crawler]
# Interval in seconds at which the feed crawler will run
interval_seconds = 60
rpc_url = "https://example.com"

# Exchange rate
[[service.feed_crawler.rates]]
description = "BTC/USD"
addresses = ["0x91D32e6f01d6473b596f54c6E304e06d774f86b2"]

# Cross rate
[[service.feed_crawler.rates]]
description = "BTC/USD/USDT"
addresses = ["0x91D32e6f01d6473b596f54c6E304e06d774f86b2", "0x023dfc789db466DD5C900DC04706727a3A9Cf3DE"]

