[service]
# Port on which the service will run
port = 30445

[service.signer]
# secpr256k1 32-byte hex-encoded private key, used for signing,
# this is a example key, do not use it anywhere else
private_key = "804622cda0d8e634317a12651d91751ceff5c081f2b5f63ef7912725c7275e5d"

[service.db] # Postgres database configuration
url = "localhost:5432"
username = "oracle"
password = "oracle"
database = "price_oracle"
max_connections = 5

[service.timekeeper]
rpc_url = "http://localhost:18443"
rpc_user = "elements"
rpc_password = "elements"
esplora_url = "http://localhost:3000"
signer_mnemonic = "exist carry drive collect lend cereal occur much tiger just involve mean"
publish_interval_seconds = 60 # Interval in seconds at which the timekeeper will publish a new timestamp
return_to_issuer_interval_seconds = 300 # Interval in seconds after which the timekeeper will return the timestamp UTXO to the issuer if not used
finalization_timeout_seconds = 300 # Time in seconds to wait for a transaction to be finalized before considering it failed
max_supply = 1000000000000000 # Maximum supply of the timestamp asset (in satoshis)
contract_json = '{"entity":{"domain":"timestamp.example.com"},"name":"Timestamp","ticker":"TIME","version":0}'

[service.feed_crawler]
interval_seconds = 60 # Interval in seconds at which the feed crawler will run
validity_seconds = 3600 
rpc_url = "https://example.com"
feeds = ["BTC/USD", "BTC/USD/USDT"]
addresses = [
    "0x91D32e6f01d6473b596f54c6E304e06d774f86b2",
    "0x023dfc789db466DD5C900DC04706727a3A9Cf3DE",
]
